### ISSUE TITLE
Access to ser2sock

### ISSUE THREAD

**Issue by DrJeff** [goyney/hassio-addon-ser2sock#1]
Can this be accessed from the base IP of the host? So that it can be used outside of Home Assistant? I also could not access from HA with ```local-ser2sock```

**Comment by DrJeff** [comment]
On my VM the address was different so I bashed into the docker
list the dockers first
```
docker ps 
```
Then bashed into ser2sock
```
docker exec -it addon_23e7fcb8_ser2sock bash
```
After bashing in I checked the hostname with
```
hostname
```
And then used that name for my configuration like so
```
  device:
    type: socket
    host: '23e7fcb8-ser2sock'
    port: 10000
```
But I still want access off this machine do you know how?
